### ISSUE TITLE
Error from Library Tag

### ISSUE THREAD

**Issue by PeteSesto** [VerveWireless/verve-android-adsdk#10]
since updating android studio to v 3.0 stable and gradle to 3, an error is generated from verve_import:

```
/Users/username/MyApplication/verve_import/build/intermediates/manifest/androidTest/debug/AndroidManifest.xml
Error:(23) error: unknown element <library> found.
Error:(23) unknown element <library> found.
```

in the generated manifest, We can see:

`<library android:name="moat-mobile-app-kit" />`

The library tag is not a valid tag.  Is it possible to get an update with this resolved?

EDIT:  noticed this was in closed issues and commented in that as well
https://github.com/VerveWireless/verve-android-adsdk/issues/9

Thank you

**Comment by christinamatthews** [comment]
Hi @PeteSesto - Please try downloading and integrating our latest release, v3.6.0, which was published today. This version includes a fix for the issue mentioned. Please let us know if the problem still persists. Thank you!

**Comment by PeteSesto** [comment]
Thank you @christinamatthews!

I apologize for spamming the issue board, just wanted to make sure you were getting alerted :)

**Comment by PeteSesto** [comment]
@christinamatthews still seeing the same issue after updating

**Comment by christinamatthews** [comment]
Hi @PeteSesto - can you send a screenshot of the error? We are unable to reproduce in the latest version. Are you by any chance using the MoPub SDK as well?

**Comment by PeteSesto** [comment]
@christinamatthews 

I slept on it and tried again today and it seems to be working (hooray!). I must have missed something in my last attempt.

Thank you so much for the quick response.

It does appear that this update has solved my issue

**Comment by christinamatthews** [comment]
Great, happy to hear that! :) Let us know if you run into any other issues!
