### ISSUE TITLE
unknown element <library>

### ISSUE THREAD

**Issue by rslama** [VerveWireless/verve-android-adsdk#11]
Hey,  after update android gradle plugin to version 3.0.0 verve sdk produce error

AGPBI: {"kind":"error","text":"error: unknown element \u003clibrary\u003e found.","sources":[{"file":"/Users/xxx/projects/prod/verve_import/build/intermediates/manifest/androidTest/debug/AndroidManifest.xml","position":{"startLine":26}}],"original":"","tool":"AAPT"}

**Comment by PeteSesto** [comment]
I reported the same issue.  This is the same as closed issue found here: https://github.com/VerveWireless/verve-android-adsdk/issues/9

That issue should not have been closed and is stopping us from being able to update the gradle version in our app as well

**Comment by christinamatthews** [comment]
Hi @rslama and @PeteSesto - Please try downloading and integrating our latest release, v3.6.0, which was published today. This version includes a fix for the issue mentioned. Please let us know if the problem still persists. Thank you!
