### ISSUE TITLE
SQLiteException crash in production

### ISSUE THREAD

**Issue by RicardoBelchior** [VerveWireless/verve-android-adsdk#13]
Hi, 

Today I woke up with 160 crash reports of an user for a SQLiteException in the verve source code. Here it is:

> Caused by android.database.sqlite.SQLiteException: no such table: geofenceEvents (code 1): , while compiling: SELECT ge.*, COALESCE(gr.name, gb.name) AS monitored_name, COALESCE(gr.segment_id, gb.segment_id) AS monitored_segment_id FROM geofenceEvents AS ge LEFT JOIN geofenceRegions AS gr ON ge.monitored = 'region' AND ge.monitored_id=gr.id LEFT JOIN geofenceBeacons AS gb ON ge.monitored = 'beacon' OR  ge.monitored ='place' OR  ge.monitored ='wifi' AND ge.monitored_id=gb.id
> #################################################################
> Error Code : 1 (SQLITE_ERROR)
> Caused By : SQL(query) error or missing database.
> 	(no such table: geofenceEvents (code 1): , while compiling: SELECT ge.*, COALESCE(gr.name, gb.name) AS monitored_name, COALESCE(gr.segment_id, gb.segment_id) AS monitored_segment_id FROM geofenceEvents AS ge LEFT JOIN geofenceRegions AS gr ON ge.monitored = 'region' AND ge.monitored_id=gr.id LEFT JOIN geofenceBeacons AS gb ON ge.monitored = 'beacon' OR  ge.monitored ='place' OR  ge.monitored ='wifi' AND ge.monitored_id=gb.id)
> #################################################################
>        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
>        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1004)
>        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:569)
>        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
>        at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:59)
>        at android.database.sqlite.SQLiteQuery.(SQLiteQuery.java:37)
>        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
>        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1480)
>        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1419)
>        at com.vervewireless.advert.adattribution.j.c(SourceFile:307)
>        at com.vervewireless.advert.adattribution.ae.a(SourceFile:75)
>        at com.vervewireless.advert.adattribution.ae.doInBackground(SourceFile:34)
>        at android.os.AsyncTask$2.call(AsyncTask.java:295)

Device info:

> Date: 2018-03-30T10:49:00Z
> OS Version: 6.0.1
> Device: Galaxy S5 Mini
> RAM Free: 24%
> Disk Free: 8.1%

Seems like a migration bug which is affecting production users.... can you have a look?

**Comment by christinamatthews** [comment]
Thank you @RicardoBelchior . We are actively investigating this issue and will respond to this thread with any updates.

**Comment by christinamatthews** [comment]
Issue resolved in v3.7.2.
