### ISSUE TITLE
Compilation Issue Version 3.2.1

### ISSUE THREAD

**Issue by B1unty** [VerveWireless/verve-android-adsdk#4]
I have downloaded the new version i.e 3.2.1 and still I am getting the same compilation issue.
I am compiling the sample project with java 1.7
![screenshot 19](https://cloud.githubusercontent.com/assets/19987794/18863538/680dbfb8-84af-11e6-8647-839e85a0ec14.png)

Information:Gradle tasks [:master_sample_application:clean, :master_sample_application:generateDebugSources, :master_sample_application:generateDebugAndroidTestSources, :master_sample_application:mockableAndroidJar, :master_sample_application:prepareDebugUnitTestDependencies, :master_sample_application:assembleDebug]
:master_sample_application:clean
:master_sample_application:preBuild UP-TO-DATE
:master_sample_application:preDebugBuild UP-TO-DATE
:master_sample_application:checkDebugManifest
:master_sample_application:preReleaseBuild UP-TO-DATE
:verve_import:preBuild UP-TO-DATE
:verve_import:preReleaseBuild UP-TO-DATE
:verve_import:compileReleaseNdk UP-TO-DATE
:verve_import:compileLint
:verve_import:copyReleaseLint UP-TO-DATE
:verve_import:checkReleaseManifest
:verve_import:preDebugAndroidTestBuild UP-TO-DATE
:verve_import:preDebugBuild UP-TO-DATE
:verve_import:preDebugUnitTestBuild UP-TO-DATE
:verve_import:preReleaseUnitTestBuild UP-TO-DATE
:verve_import:prepareComAndroidSupportAppcompatV72221Library UP-TO-DATE
:verve_import:prepareComAndroidSupportRecyclerviewV72221Library UP-TO-DATE
:verve_import:prepareComAndroidSupportSupportV42300Library UP-TO-DATE
:verve_import:prepareComGoogleAndroidGmsPlayServicesAds840Library UP-TO-DATE
:verve_import:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:verve_import:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:verve_import:prepareComGoogleAndroidGmsPlayServicesLocation840Library UP-TO-DATE
:verve_import:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:verve_import:prepareOrgAltbeaconAndroidBeaconLibrary261Library UP-TO-DATE
:verve_import:prepareSampleProjectsRoximitySdk2020UnspecifiedLibrary UP-TO-DATE
:verve_import:prepareSampleProjectsVRVMoatMobileAppKit176UnspecifiedLibrary UP-TO-DATE
:verve_import:prepareSampleProjectsVerve_AdSDK_321UnspecifiedLibrary UP-TO-DATE
:verve_import:prepareReleaseDependencies
:verve_import:compileReleaseAidl UP-TO-DATE
:verve_import:compileReleaseRenderscript UP-TO-DATE
:verve_import:generateReleaseBuildConfig UP-TO-DATE
:verve_import:mergeReleaseShaders UP-TO-DATE
:verve_import:compileReleaseShaders UP-TO-DATE
:verve_import:generateReleaseAssets UP-TO-DATE
:verve_import:mergeReleaseAssets UP-TO-DATE
:verve_import:generateReleaseResValues UP-TO-DATE
:verve_import:generateReleaseResources UP-TO-DATE
:verve_import:mergeReleaseResources UP-TO-DATE
:verve_import:processReleaseManifest UP-TO-DATE
:verve_import:processReleaseResources
:verve_import:generateReleaseSources
:verve_import:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:verve_import:compileReleaseJavaWithJavac UP-TO-DATE
:verve_import:extractReleaseAnnotations UP-TO-DATE
:verve_import:mergeReleaseProguardFiles UP-TO-DATE
:verve_import:packageReleaseRenderscript UP-TO-DATE
:verve_import:packageReleaseResources UP-TO-DATE
:verve_import:processReleaseJavaRes UP-TO-DATE
:verve_import:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:verve_import:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:verve_import:mergeReleaseJniLibFolders UP-TO-DATE
:verve_import:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:verve_import:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:verve_import:bundleRelease UP-TO-DATE
:master_sample_application:prepareComAndroidSupportAppcompatV72221Library
:master_sample_application:prepareComAndroidSupportRecyclerviewV72221Library
:master_sample_application:prepareComAndroidSupportSupportV42300Library
:master_sample_application:prepareComGoogleAndroidGmsPlayServicesAds840Library
:master_sample_application:prepareComGoogleAndroidGmsPlayServicesBase840Library
:master_sample_application:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:master_sample_application:prepareComGoogleAndroidGmsPlayServicesLocation840Library
:master_sample_application:prepareComGoogleAndroidGmsPlayServicesMaps840Library
:master_sample_application:prepareComMopubMopubSdk3100Library
:master_sample_application:prepareOrgAltbeaconAndroidBeaconLibrary261Library
:master_sample_application:prepareSampleProjectsRoximitySdk2020UnspecifiedLibrary
:master_sample_application:prepareSampleProjectsVRVMoatMobileAppKit176UnspecifiedLibrary
:master_sample_application:prepareSampleProjectsVerve_AdSDK_321UnspecifiedLibrary
:master_sample_application:prepareSampleProjectsVerve_importUnspecifiedLibrary
:master_sample_application:prepareDebugDependencies
:master_sample_application:compileDebugAidl
:master_sample_application:compileDebugRenderscript
:master_sample_application:generateDebugBuildConfig
:master_sample_application:mergeDebugShaders
:master_sample_application:compileDebugShaders
:master_sample_application:generateDebugAssets
:master_sample_application:mergeDebugAssets
:master_sample_application:generateDebugResValues UP-TO-DATE
:master_sample_application:generateDebugResources
:master_sample_application:mergeDebugResources
:master_sample_application:processDebugManifest
E:\verve3.2\Sample Projects\master_sample_application\src\main\AndroidManifest.xml:42:9-46:20 Warning:
	receiver#com.roximity.system.BootReceiver was tagged at AndroidManifest.xml:42 to remove other declarations but no other declaration present
E:\verve3.2\Sample Projects\master_sample_application\src\main\AndroidManifest.xml:49:9-58:20 Warning:
	receiver#com.roximity.system.GCMReceiver was tagged at AndroidManifest.xml:49 to remove other declarations but no other declaration present
E:\verve3.2\Sample Projects\master_sample_application\src\main\AndroidManifest.xml:29:5-31:31 Warning:
	uses-permission#com.google.android.c2dm.permission.RECEIVE was tagged at AndroidManifest.xml:29 to remove other declarations but no other declaration present
E:\verve3.2\Sample Projects\master_sample_application\src\main\AndroidManifest.xml:33:5-36:31 Warning:
	permission#com.roximity.locator.permission.C2D_MESSAGE was tagged at AndroidManifest.xml:33 to remove other declarations but no other declaration present
E:\verve3.2\Sample Projects\master_sample_application\src\main\AndroidManifest.xml:38:5-40:31 Warning:
	uses-permission#com.roximity.locator.permission.C2D_MESSAGE was tagged at AndroidManifest.xml:38 to remove other declarations but no other declaration present
:master_sample_application:processDebugResources
:master_sample_application:generateDebugSources
:master_sample_application:preDebugAndroidTestBuild UP-TO-DATE
:master_sample_application:prepareDebugAndroidTestDependencies
:master_sample_application:compileDebugAndroidTestAidl
:master_sample_application:processDebugAndroidTestManifest
:master_sample_application:compileDebugAndroidTestRenderscript
:master_sample_application:generateDebugAndroidTestBuildConfig
:master_sample_application:mergeDebugAndroidTestShaders
:master_sample_application:compileDebugAndroidTestShaders
:master_sample_application:generateDebugAndroidTestAssets
:master_sample_application:mergeDebugAndroidTestAssets
:master_sample_application:generateDebugAndroidTestResValues UP-TO-DATE
:master_sample_application:generateDebugAndroidTestResources
:master_sample_application:mergeDebugAndroidTestResources
:master_sample_application:processDebugAndroidTestResources
:master_sample_application:generateDebugAndroidTestSources
:master_sample_application:mockableAndroidJar UP-TO-DATE
:master_sample_application:preDebugUnitTestBuild UP-TO-DATE
:master_sample_application:prepareDebugUnitTestDependencies
:master_sample_application:incrementalDebugJavaCompilationSafeguard
:master_sample_application:compileDebugJavaWithJavac
:master_sample_application:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:master_sample_application:compileDebugNdk UP-TO-DATE
:master_sample_application:compileDebugSources
:master_sample_application:buildInfoDebugLoader
:master_sample_application:transformClassesWithExtractJarsForDebug
:master_sample_application:transformClassesWithInstantRunVerifierForDebug
:master_sample_application:transformClassesWithJavaResourcesVerifierForDebug
:master_sample_application:mergeDebugJniLibFolders
:master_sample_application:transformNative_libsWithMergeJniLibsForDebug
:master_sample_application:processDebugJavaRes UP-TO-DATE
:master_sample_application:transformResourcesWithMergeJavaResForDebug
:master_sample_application:transformResourcesAndNative_libsWithJavaResourcesVerifierForDebug
:master_sample_application:transformClassesWithInstantRunForDebug
:master_sample_application:transformClasses_enhancedWithInstant+reloadDexForDebug
:master_sample_application:incrementalDebugTasks
:master_sample_application:prePackageMarkerForDebug
:master_sample_application:fastDeployDebugExtractor
:master_sample_application:generateDebugInstantRunAppInfo
:master_sample_application:coldswapKickerDebug
:master_sample_application:transformClassesWithInstantRunSlicerForDebug
:master_sample_application:transformClassesWithDexForDebug
To run dex in process, the Gradle daemon needs a larger heap.
It currently has approximately 910 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to more than 2048 MB.
To do this set org.gradle.jvmargs=-Xmx2048M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
Error:1 error; aborting
:master_sample_application:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':master_sample_application:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 1 mins 47.888 secs
Information:3 errors
Information:0 warnings
Information:See complete output in console

**Comment by bharatbiswal** [comment]
I have the same issue as well. Sample master app fails to compile.

**Comment by christinalong** [comment]
@B1unty @bharatbiswal - This is a known issue. To resolve, please either 1) Disable Instant Run or 2) Change the gradle plug in version to 2.1.0.

<img width="687" alt="screen shot 2016-09-27 at 9 41 48 am" src="https://cloud.githubusercontent.com/assets/5808791/18876189/b70fc66a-8496-11e6-91d0-9e7ce6bf3c60.png">
