### ISSUE TITLE
Unnecessary enforcement of `VerveAdHandler` for mediation

### ISSUE THREAD

**Issue by jhansche** [VerveWireless/verve-android-adsdk#5]
There is an interface that the built-in `com.mopub.mobileads.VerveBanner` class enforces must be implemented by all Activity classes that host a Verve ad. The only purpose of this `VerveAdHandler` interface is to provide a listener to the Activity.  And the only purpose of providing that listener is so the Activity can notify the AdView of `onPause()` and `onResume()` events.

This causes unnecessary technical debt to an application, by sprinkling this interface throughout every Activity class in the app. In principle, an ad SDK should not be tied to application's or even activity's lifecycle -- at least not during mediation.  Instead, it is only tied to the request for an ad.  MoPub (for example) notifies the SDK when it wants an ad (via `loadBanner()`), and when it no longer needs that ad (via `onInvalidate()`).  The Ad SDK should have no need to be aware of anything else about the application.

In the event the SDK does still need to know about pause and resume events, it's very simple to provide that, using the `Application.registerActivityLifecycleCallbacks()` and `unregisterActivityLifecycleCallbacks()` methods.  That can be registered in `onAdLoaded()` (when MoPub is notified of `onBannerLoaded()`), and can be unregistered in `onInvalidate()`. Then in the ActivityLifecycleCallbacks implementation, simply pass through the calls to `AdView.onResume()` and `AdView.onPause(activity.isFinishing())`.

**Comment by christinalong** [comment]
Thank you, @jhansche, for the detailed feedback. We are actively working on new architecture to remove the VerveAdHandler dependency and will keep you updated when released.

**Comment by christinalong** [comment]
This is resolved in v3.3.0.
