### ISSUE TITLE
AAPT2 Link Failed with Gradle Plugin 3.0.0-alpha2

### ISSUE THREAD

**Issue by sankartringapps** [VerveWireless/verve-android-adsdk#9]
When I include Moat Mobile app kit in the project am getting the below error only while using the latest gradle plugin 3.0.0-alpha2.

**Error:** `../app/build/intermediates/manifests/full/flavorName/debug/AndroidManifest.xml:64 unknown element <library> found`

The line at AndroidManifest.xml: 64 in the merged manifest is `<library android:name="moat-mobile-app-kit" />`

Adding `<library tools:node="removeAll"/>` to the main manifest outside of the `<application>` tag fixes the issue. Is this the proper fix or is this an issue with latest Android Studio?

**Environment:**
- Android Studio - 3.0 Canary 2
- Gradle Plugin - 3.0.0-alpha2
- Gradle Distribution - 4.0-milestone-1

**Comment by christinamatthews** [comment]
Hi @sankartringapps. We have investigated this issue and believe that there is a bug in the alpha version of the Gradle plugin. Please try using a non-alpha version of the plugin and reopen this ticket if you still see the issue there (or in the final 3.0.0 release of the plugin). Thanks!

**Comment by PeteSesto** [comment]
Experiencing this same issue with gradle 3.0 stable and android studio 3.0 stable

**Comment by verveappbuilder** [comment]
Hi @PeteSesto - Please try downloading and integrating our latest release, v3.6.0, which was published today. This version includes a fix for the issue mentioned. Please let us know if the problem still persists. Thank you!

**Comment by christinamatthews** [comment]
@sankartringapps - Please try downloading and integrating our latest release, v3.6.0, which was published today. This version includes a fix for the issue mentioned. Please let us know if the problem still persists. Thank you!
